spring:
    application:
        name: service-zuul-service
server:
    port: 8090

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
zuul:
    routes:
        store:
            service-id: service-store   
            path: /api/store/**
        celulares:
            service-id: service-celulares
            path: /api/celulares/**

        usuarios:
            service-id: service-usuarios
            path: /api/us/**