server:
    port: 8082
spring:
    application:
        name: service-store
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
ribbon:
    ConnectTimeout: 3000
    ReadTimeout: 10000
hytrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 2000