spring:
  application:
    name: service-usuarios
server:
  port: 8070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  # instance:
  #   instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #   leaseRenewalIntervalInSeconds: 1
  #   leaseExpirationDurationInSeconds: 2
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG